import React, { useEffect } from 'react';
import Sidebar from './Sidebar';
import { useNavigate } from 'react-router-dom';

export const Home: React.FC = () => {

  // const BASE_URL = "http://localhost:5000";
  const BASE_URL = "https://share-bill-api.vercel.app";

  const navigate = useNavigate();

  const getData = async () => {
    try {
      const res = await fetch(`${BASE_URL}/user`, {
        method: 'GET',
        headers: {
          'Content-Type': 'application/json'
        },
        credentials: 'include',
      });

      // const data = await res.json();
      if (res.status !== 200) {
        navigate('/login');
      }

    } catch (error) {
      console.log(error);
    }
  }

  useEffect(() => {
    getData();
  }, [])

  return (
    <div className="home-container">
      <Sidebar />
      <div className="home-AddNew">
        <div className="home-AddNew-empty">
          Select the bill
        </div>
      </div>








      {/* <h1 className="">Redux + TypeScript</h1>
      <p>
        Hello and welcome! :) This app was generated by the Create React App
        template and bootstrapped with Redux, React Router, React Testing
        Library, TypeScript, ESlint, Prettier for you. Take a look around ;)
      </p> */}
    </div>
  )
}
